// This script connects to MongoDB and seeds it with an initial list of cities.

require('dotenv').config();
const { MongoClient } = require('mongodb');

// Your MongoDB connection string from the .env file
const mongoUri = process.env.MONGO_URI;

// The list of 200 major cities
const cities = [
  { name: 'Mumbai', location: 'Maharashtra' },
  { name: 'Delhi', location: 'Delhi' },
  { name: 'Bengaluru', location: 'Karnataka' },
  { name: 'Kolkata', location: 'West Bengal' },
  { name: 'Chennai', location: 'Tamil Nadu' },
  { name: 'Hyderabad', location: 'Telangana' },
  { name: 'Pune', location: 'Maharashtra' },
  { name: 'Ahmedabad', location: 'Gujarat' },
  { name: 'Surat', location: 'Gujarat' },
  { name: 'Lucknow', location: 'Uttar Pradesh' },
  { name: 'Jaipur', location: 'Rajasthan' },
  { name: 'Kanpur', location: 'Uttar Pradesh' },
  { name: 'Nagpur', location: 'Maharashtra' },
  { name: 'Indore', location: 'Madhya Pradesh' },
  { name: 'Thane', location: 'Maharashtra' },
  { name: 'Bhopal', location: 'Madhya Pradesh' },
  { name: 'Visakhapatnam', location: 'Andhra Pradesh' },
  { name: 'Pimpri-Chinchwad', location: 'Maharashtra' },
  { name: 'Patna', location: 'Bihar' },
  { name: 'Vadodara', location: 'Gujarat' },
  { name: 'Ghaziabad', location: 'Uttar Pradesh' },
  { name: 'Ludhiana', location: 'Punjab' },
  { name: 'Agra', location: 'Uttar Pradesh' },
  { name: 'Nashik', location: 'Maharashtra' },
  { name: 'Faridabad', location: 'Haryana' },
  { name: 'Meerut', location: 'Uttar Pradesh' },
  { name: 'Rajkot', location: 'Gujarat' },
  { name: 'Kalyan-Dombivali', location: 'Maharashtra' },
  { name: 'Vasai-Virar', location: 'Maharashtra' },
  { name: 'Varanasi', location: 'Uttar Pradesh' },
  { name: 'Srinagar', location: 'Jammu and Kashmir' },
  { name: 'Aurangabad', location: 'Maharashtra' },
  { name: 'Dhanbad', location: 'Jharkhand' },
  { name: 'Amritsar', location: 'Punjab' },
  { name: 'Navi Mumbai', location: 'Maharashtra' },
  { name: 'Allahabad', location: 'Uttar Pradesh' },
  { name: 'Ranchi', location: 'Jharkhand' },
  { name: 'Howrah', location: 'West Bengal' },
  { name: 'Coimbatore', location: 'Tamil Nadu' },
  { name: 'Jabalpur', location: 'Madhya Pradesh' },
  { name: 'Gwalior', location: 'Madhya Pradesh' },
  { name: 'Vijayawada', location: 'Andhra Pradesh' },
  { name: 'Jodhpur', location: 'Rajasthan' },
  { name: 'Madurai', location: 'Tamil Nadu' },
  { name: 'Raipur', location: 'Chhattisgarh' },
  { name: 'Kota', location: 'Rajasthan' },
  { name: 'Guwahati', location: 'Assam' },
  { name: 'Chandigarh', location: 'Chandigarh' },
  { name: 'Solapur', location: 'Maharashtra' },
  { name: 'Hubli-Dharwad', location: 'Karnataka' },
  { name: 'Bareilly', location: 'Uttar Pradesh' },
  { name: 'Moradabad', location: 'Uttar Pradesh' },
  { name: 'Mysore', location: 'Karnataka' },
  { name: 'Gurgaon', location: 'Haryana' },
  { name: 'Aligarh', location: 'Uttar Pradesh' },
  { name: 'Jalandhar', location: 'Punjab' },
  { name: 'Tiruchirappalli', location: 'Tamil Nadu' },
  { name: 'Bhubaneswar', location: 'Odisha' },
  { name: 'Salem', location: 'Tamil Nadu' },
  { name: 'Mira-Bhayandar', location: 'Maharashtra' },
  { name: 'Thiruvananthapuram', location: 'Kerala' },
  { name: 'Bhiwandi', location: 'Maharashtra' },
  { name: 'Saharanpur', location: 'Uttar Pradesh' },
  { name: 'Gorakhpur', location: 'Uttar Pradesh' },
  { name: 'Guntur', location: 'Andhra Pradesh' },
  { name: 'Bikaner', location: 'Rajasthan' },
  { name: 'Amravati', location: 'Maharashtra' },
  { name: 'Noida', location: 'Uttar Pradesh' },
  { name: 'Jamshedpur', location: 'Jharkhand' },
  { name: 'Bhilai', location: 'Chhattisgarh' },
  { name: 'Warangal', location: 'Telangana' },
  { name: 'Cuttack', location: 'Odisha' },
  { name: 'Firozabad', location: 'Uttar Pradesh' },
  { name: 'Kochi', location: 'Kerala' },
  { name: 'Bhavnagar', location: 'Gujarat' },
  { name: 'Dehradun', location: 'Uttarakhand' },
  { name: 'Durgapur', location: 'West Bengal' },
  { name: 'Asansol', location: 'West Bengal' },
  { name: 'Nanded', location: 'Maharashtra' },
  { name: 'Kolhapur', location: 'Maharashtra' },
  { name: 'Ajmer', location: 'Rajasthan' },
  { name: 'Gulbarga', location: 'Karnataka' },
  { name: 'Jamnagar', location: 'Gujarat' },
  { name: 'Ujjain', location: 'Madhya Pradesh' },
  { name: 'Loni', location: 'Uttar Pradesh' },
  { name: 'Siliguri', location: 'West Bengal' },
  { name: 'Jhansi', location: 'Uttar Pradesh' },
  { name: 'Ulhasnagar', location: 'Maharashtra' },
  { name: 'Nellore', location: 'Andhra Pradesh' },
  { name: 'Jammu', location: 'Jammu and Kashmir' },
  { name: 'Sangli-Miraj & Kupwad', location: 'Maharashtra' },
  { name: 'Belgaum', location: 'Karnataka' },
  { name: 'Mangalore', location: 'Karnataka' },
  { name: 'Ambattur', location: 'Tamil Nadu' },
  { name: 'Tirunelveli', location: 'Tamil Nadu' },
  { name: 'Malegaon', location: 'Maharashtra' },
  { name: 'Gaya', location: 'Bihar' },
  { name: 'Jalgaon', location: 'Maharashtra' },
  { name: 'Udaipur', location: 'Rajasthan' },
  { name: 'Maheshtala', location: 'West Bengal' },
  { name: 'Tiruppur', location: 'Tamil Nadu' },
  { name: 'Davanagere', location: 'Karnataka' },
  { name: 'Kozhikode', location: 'Kerala' },
  { name: 'Akola', location: 'Maharashtra' },
  { name: 'Kurnool', location: 'Andhra Pradesh' },
  { name: 'Bokaro Steel City', location: 'Jharkhand' },
  { name: 'Rajahmundry', location: 'Andhra Pradesh' },
  { name: 'Ballari', location: 'Karnataka' },
  { name: 'Agartala', location: 'Tripura' },
  { name: 'Bhagalpur', location: 'Bihar' },
  { name: 'Latur', location: 'Maharashtra' },
  { name: 'Dhule', location: 'Maharashtra' },
  { name: 'Korba', location: 'Chhattisgarh' },
  { name: 'Bhilwara', location: 'Rajasthan' },
  { name: 'Brahmapur', location: 'Odisha' },
  { name: 'Muzaffarpur', location: 'Bihar' },
  { name: 'Ahmednagar', location: 'Maharashtra' },
  { name: 'Mathura', location: 'Uttar Pradesh' },
  { name: 'Kollam', location: 'Kerala' },
  { name: 'Avadi', location: 'Tamil Nadu' },
  { name: 'Kadapa', location: 'Andhra Pradesh' },
  { name: 'Kamarhati', location: 'West Bengal' },
  { name: 'Sambalpur', location: 'Odisha' },
  { name: 'Bilaspur', location: 'Chhattisgarh' },
  { name: 'Shahjahanpur', location: 'Uttar Pradesh' },
  { name: 'Satara', location: 'Maharashtra' },
  { name: 'Thrissur', location: 'Kerala' },
  { name: 'Alwar', location: 'Rajasthan' },
  { name: 'Kakinada', location: 'Andhra Pradesh' },
  { name: 'Panipat', location: 'Haryana' },
  { name: 'Darbhanga', location: 'Bihar' },
  { name: 'Rourkela', location: 'Odisha' },
  { name: 'Nizamabad', location: 'Telangana' },
  { name: 'Parbhani', location: 'Maharashtra' },
  { name: 'Tumkur', location: 'Karnataka' },
  { name: 'Hisar', location: 'Haryana' },
  { name: 'Ozhukarai', location: 'Puducherry' },
  { name: 'Bihar Sharif', location: 'Bihar' },
  { name: 'Panvel', location: 'Maharashtra' },
  { name: 'Durg', location: 'Chhattisgarh' },
  { name: 'Naihati', location: 'West Bengal' },
  { name: 'Tirupati', location: 'Andhra Pradesh' },
  { name: 'Ichalkaranji', location: 'Maharashtra' },
  { name: 'Bathinda', location: 'Punjab' },
  { name: 'Sikar', location: 'Rajasthan' },
  { name: 'Karimnagar', location: 'Telangana' },
  { name: 'Anantapur', location: 'Andhra Pradesh' },
  { name: 'Puducherry', location: 'Puducherry' },
  { name: 'Gandhinagar', location: 'Gujarat' },
  { name: 'Shimla', location: 'Himachal Pradesh' },
  { name: 'Port Blair', location: 'Andaman and Nicobar Islands' },
  { name: 'Aizawl', location: 'Mizoram' },
  { name: 'Imphal', location: 'Manipur' },
  { name: 'Shillong', location: 'Meghalaya' },
  { name: 'Gangtok', location: 'Sikkim' },
  { name: 'Panaji', location: 'Goa' },
  { name: 'Kavaratti', location: 'Lakshadweep' },
  { name: 'Silvassa', location: 'Dadra and Nagar Haveli' },
  { name: 'Daman', location: 'Daman and Diu' },
  { name: 'Itanagar', location: 'Arunachal Pradesh' },
  { name: 'Kohima', location: 'Nagaland' },
  { name: 'Dispur', location: 'Assam' },
  { name: 'Khandwa', location: 'Madhya Pradesh' },
  { name: 'Ratlam', location: 'Madhya Pradesh' },
  { name: 'Rewa', location: 'Madhya Pradesh' },
  { name: 'Satna', location: 'Madhya Pradesh' },
  { name: 'Sagar', location: 'Madhya Pradesh' },
  { name: 'Singrauli', location: 'Madhya Pradesh' },
  { name: 'Burhanpur', location: 'Madhya Pradesh' },
  { name: 'Muzaffarnagar', location: 'Uttar Pradesh' },
  { name: 'Etawah', location: 'Uttar Pradesh' },
  { name: 'Hapur', location: 'Uttar Pradesh' },
  { name: 'Rampur', location: 'Uttar Pradesh' },
  { name: 'Nawabganj', location: 'Uttar Pradesh' },
  { name: 'Farrukhabad', location: 'Uttar Pradesh' },
  { name: 'Pali', location: 'Rajasthan' },
  { name: 'Sri Ganganagar', location: 'Rajasthan' },
  { name: 'Bharatpur', location: 'Rajasthan' },
  { name: 'Purnia', location: 'Bihar' },
  { name: 'Arrah', location: 'Bihar' },
  { name: 'Begusarai', location: 'Bihar' },
  { name: 'Katihar', location: 'Bihar' }
];

async function seedDB() {
  const client = new MongoClient(mongoUri);
  try {
    console.log("Connecting to the database...");
    await client.connect();
    console.log("✅ Successfully connected to MongoDB!");

    const db = client.db('tourismApp');
    const collection = db.collection('destinations');

    console.log("Deleting existing destinations...");
    await collection.deleteMany({});
    console.log("✅ Existing destinations deleted.");

    console.log("Inserting new city list...");
    await collection.insertMany(cities);
    console.log(`✅ Database seeded with ${cities.length} cities!`);

  } catch (err) {
    console.error('❌ FAILED TO SEED DATABASE:', err);
  } finally {
    console.log("Closing database connection.");
    await client.close();
  }
}

seedDB();